### ISSUE TITLE
Do you plan to publish new images?

### ISSUE THREAD

**Issue by sneko** [claranet/gcloud-kubectl-docker#9]
Hi @chriscoester ,

We use this image since with `bitnami/kubectl` we were unable to run Groovy syntax, and the Google one was using v1.13 at time of testing.

Now we upgrading to Kubernetes >= 1.21 and some `kubectl apply` commands are no longer valid with apiVersion. I see there is no update for more than a year, do you plan to keep going with this repo?

_On my side I tried a new time the `bitnami` image but it seems still stuck (due to Groovy?)_

Thank you,

**Comment by sneko** [comment]
At the end after testing multiple images it works with `dtzar/helm-kubectl`. So it's a good replacement, seems maintained for now with lot of downloads.

I could have use your script to manage on my own the image, but it's always hard to maintain while being alone... just wanted to rely on something used.

_By the way... never understood why the `bitnami/kubectl` has never worked. I did set the `entrypoint` to `/bin/sh` but my CI/CD pipeline has never been able to run the container properly._

**Comment by hashbou** [comment]
Hello, thank you for your request. I am very glad you could find an alternative and sorry for the (huge) delay in answering. I've now updated the repository to be functioning again. Some things were deprecated and the GitHub action was deactivated due to lack of activity. 
I'll close this issue as the tooling should now be available in the latest versions.
